import localFont from "next/font/local";
import "./globals.css";
import ProtectedRoute from "./ProtectedRoute";
import { TradeDataProvider } from '../app/components/TradeDataContext';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "ProfitONN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute>
          <TradeDataProvider>
            {children}
        </TradeDataProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}
